using FrenchNouns.AllConstants;

namespace FrenchNouns.AllNounRepository;

public static partial class NounRepository
{
    public static readonly IReadOnlyList<string> J = new[]
    {
        Constants.Journee,
        Constants.Jalousie,
        Constants.Jet,
        Constants.Joueur,
        Constants.Junior,
        Constants.Jonquille,
        Constants.Jambe,
        Constants.Jean,
        Constants.Joue,
        Constants.Japonais,
        Constants.Jardin,
        Constants.Jour,
        Constants.Jouet,
        Constants.Journal,
        Constants.Jupe,
        Constants.Juillet,
        Constants.Janvier,
        Constants.Jeu,
        Constants.Jardinier,
        Constants.Jardiniere,
        Constants.Jeune,
        Constants.Jeunesse,
        Constants.Joystick,
        Constants.Journaliste,
        Constants.Jus,
        Constants.Juin,
        Constants.Jambon,
        Constants.Jeton,
        Constants.Joie,
        Constants.Jongleur,
        Constants.Juge,
        Constants.Jeudi,
        Constants.Justice,
        Constants.Jumeau,
        Constants.Joyau,
        Constants.Jugement,
        Constants.Juteux,
        Constants.Jasmin,
        Constants.Jumelle,
        Constants.Jupon,
        Constants.Jarret,
        Constants.Jachere,
        Constants.Javelot,
        Constants.Jetee,
        Constants.Joaillier,
        Constants.Jungle,
        Constants.Juriste,
        Constants.Juridiction,
        Constants.Jubile,
        Constants.Jarre,

        //

        Constants.Plural_Jambieres
    };

    public static readonly IReadOnlyList<string> J_Popular = new[]
    {
        Constants.Jalousie,
        Constants.Jambe,
        Constants.Jambon,
        Constants.Janvier,
        Constants.Jardin,
        Constants.Jardinier,
        Constants.Jardiniere,
        Constants.Jean,
        Constants.Jeu,
        Constants.Jeudi,
        Constants.Jeune,
        Constants.Jeunesse,
        Constants.Joie,
        Constants.Jonquille,
        Constants.Joue,
        Constants.Jouet,
        Constants.Joueur,
        Constants.Journal,
        Constants.Journaliste,
        Constants.Journee,
        Constants.Juge,
        Constants.Jugement,
        Constants.Juillet,
        Constants.Juin,
        Constants.Jumeau,
        Constants.Jumelle,
        Constants.Jungle,
        Constants.Jupe,
        Constants.Juriste,
        Constants.Jus,
        Constants.Justice,
        Constants.Jasmin,
        Constants.Jetee,
        Constants.Joyau,
        Constants.Jubile,
        Constants.Juridiction,
        Constants.Jour,
        Constants.Joaillier,
    };
}
