using FrenchNouns.AllConstants;

namespace FrenchNouns.AllNounRepository;

public static partial class NounRepository
{
    public static readonly IReadOnlyList<string> L = new[]
    {
        Constants.Loisir,
        Constants.Localite,
        Constants.Lateral,
        Constants.Lien,
        Constants.Limbe,
        Constants.Local,
        Constants.Lendemain,
        Constants.Lettrage,
        Constants.Lore,
        Constants.Liberte,
        Constants.Lamentation,
        Constants.Larme,
        Constants.Logement,
        Constants.Lezard,
        Constants.Lutin,
        Constants.Lacet,
        Constants.Laser,
        Constants.Laie,
        Constants.Loup,
        Constants.Laisse,
        Constants.Laine,
        Constants.Lentille,
        Constants.Lanterne,
        Constants.Litterature,
        Constants.Lion,
        Constants.Lampe,
        Constants.Langue,
        Constants.Levre,
        Constants.Lapin,
        Constants.Laitue,
        Constants.Liste,
        Constants.Legume,
        Constants.Livreur,
        Constants.Lundi,
        Constants.Lecon,
        Constants.Lance,
        Constants.Lettre,
        Constants.Lycee,
        Constants.Lit,
        Constants.Livre,
        Constants.Lune,
        Constants.Lait,
        Constants.Lieu,
        Constants.Loi,
        Constants.Labo,
        Constants.Laboratoire,
        Constants.Langage,
        Constants.Larcin,
        Constants.Laverie,
        Constants.Lecture,
        Constants.Legende,
        Constants.Limite,
        Constants.Logique,
        Constants.Louange,
        Constants.Luxe,
        Constants.Loutre,
        Constants.Lavabo,
        Constants.Lierre,
        Constants.Losange,
        Constants.Lueur,
        Constants.Luge,
        Constants.Lessive,
        Constants.Linge,
        Constants.Lucarne,
        Constants.Loyer,

        //

        Constants.Plural_Lunettes,
    };
}
